type: object
required: ['stage', 'io']
properties:
  stage:
    type: string
  io:
    type: object
    required: ['out_doc_path', 'out_stats_path']
    properties:
      out_doc_path:
        type: string
      out_stats_path:
        type: string
  detection:
    type: object
    properties:
      sample_bytes:
        type: integer
      minimum_confidence:
        type: number
  normalization:
    type: object
    properties:
      enabled:
        type: boolean
      out_dir:
        type: string
      newline_policy:
        type: string
      errors:
        type: string
