profile: dev
thresholds:
  ocr_low_conf: 60
  ocr_low_text_min_words: 8
  table_candidate_min_conf: 0.5
  suspicious_text_chars_min: 150
  low_conf_pages_ratio_review: 0.25
  multi_column_left_thr: 0.4
  multi_column_right_thr: 0.6
features:
  tables_mode: extract
  image_morph_detection: true
  text_alignment_detection: true
