stage: encoding
io:
  out_doc_path: outputs/encoding_unified_document.json
  out_stats_path: outputs/encoding_stage_stats.json
detection:
  sample_bytes: 65536
  minimum_confidence: 0.5
normalization:
  enabled: false
  newline_policy: lf
  errors: strict
