profile: prod
thresholds:
  ocr_low_conf: 70
  ocr_low_text_min_words: 10
  table_candidate_min_conf: 0.60
  suspicious_text_chars_min: 200
  low_conf_pages_ratio_review: 0.15
  multi_column_left_thr: 0.45
  multi_column_right_thr: 0.55
features:
  tables_mode: detect # detect | extract
  image_morph_detection: true
  text_alignment_detection: true
