name: "Python Setup"
description: "Set up Python with pip cache and install requirements"

inputs:
  python-version:
    description: "Python version, e.g. 3.12"
    required: false
    default: "3.12"

runs:
  using: "composite"
  steps:
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}
        cache: "pip"

    - name: Upgrade pip
      shell: bash
      run: python -m pip install --upgrade pip

    - name: Install requirements (if present)
      shell: bash
      run: |
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt || true; fi
        python .github/actions/python-setup/ensure_pytest.py
