stage: detect_type
io:
  out_doc_path: outputs/detect_type_unified_document.json
  out_stats_path: outputs/detect_type_stage_stats.json

detection:
  sample_pages: 5
  topk_image_pages: 2
  img_area_thr: 0.35
  text_len_thr: 200
  words_thr: 15
  blocks_thr: 3

